- name: Open port 80 for wordpress
  become: yes
  ufw:
    rule: allow
    port: '80'

- name: Open port for ssh
  become: yes
  ufw:
    rule: allow
    port: '22'

- name: Enable UFW
  become: yes
  ufw:
    state: enabled
